# frozen_string_literal: true

desc 'Run chunked rspec tests on specific qty, sample: CI_JOBS=3 CI_JOB=1 rake rspec_chunked'
task rspec_chunked: :environment do
  qty_jobs = (ENV['CI_JOBS'] || 3).to_i
  job_number = (ENV['CI_JOB'] || 1).to_i
  service = RspecChunked::ChunkedTests.new(qty_jobs, job_number, cmd: ENV['CI_CMD'])
  service.run
  copy_coverage
end

def copy_coverage
  path = 'coverage/.resultset.json'
  FileUtils.cp path, "coverage/.resultset-#{job_number}.json" if File.exist?(path)
end

namespace :rspec_chunked do
  desc 'Collates all result sets generated by the different test runners'
  task :merge_reports do
    require 'simplecov'
    SimpleCov.collate Dir['coverage/.resultset-*']
  end
end
