name: Ruby Gem

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Tests and Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install bundler
        run: gem install bundler && bundle install --jobs 4 --retry 3

      - name: Tests (rspec)
        run: |
          bundle exec rspec

      - name: Code style (Rubocop)
        run: bundle exec rubocop